In [ ]:
import numpy as np

In [ ]:
my_array = np.array([[[[1,3,4]]]])
np.array(my_array, ndmin=5)
my_array.ndim

4

In [ ]:
Array1 = np.array([[1, 2, 3], [4, 5, 6]]) 
Array2 = np.array([[2, 3],[3, 2]])

array3 = np.dot(Array1, Array2)

ValueError: ignored

In [ ]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])

array[::-1]

array([192, 402,  30, 302,  20, 204, 404, 203,   1,   3,  10])

In [ ]:
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]  
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [ ]:
a = np.arange(3*4*5*6).reshape((3,4,5,6)) 
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3)) 
np.dot(a, b)[2,3,2,1,2,2]

499128

In [ ]:
a = np.array([3, 7, 32], dtype = complex); print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [ ]:
ar = np.random.seed(100) 
ar1 = np.random.uniform(1,50, 20)

print(ar)
print(ar1)

ar2 = np.where(ar1 < 10, 10, np.where(ar1 > 30, 30, ar1))
print(ar2)

ar3 = np.clip(ar1, a_min=10, a_max=30)
print(ar3)

None
[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


In [ ]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
# array1, array2 = array1.flatten(), array2.flatten()
# z = np.stack((array1, array2[0:2]), axis=1)
# x = np.stack((z, array2[2:4]), axis=1)
# print(z)

In [ ]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])  
Elem_to_be_inserted = [1,2,3,4]

n_ar = np.insert(array1, 4, Elem_to_be_inserted)
print(n_ar)

[1 2 3 4 1 2 3 4]


In [ ]:
np.full((3,3), 'k')

array([['k', 'k', 'k'],
       ['k', 'k', 'k'],
       ['k', 'k', 'k']], dtype='<U1')

In [ ]:
def bub_sort(array): 
  for i in range(0, len(array)): 
    for j in range(0, len(array) - i - 1): 
      if array[j] < array[j + 1]: 
        temp = array[j] 
        array[j] = array[j + 1] 
        array[j+1] = temp 
  return array 

my_array = np.array([20,14,25,16,45,60,12,9])
bub_sort(my_array)

array([60, 45, 25, 20, 16, 14, 12,  9])

In [ ]:
ar = np.random.randint(1,10,(2,5))
# ar = np.reshape((2,5) == (5,2)) -- this won't work
print(ar)
ar1 = ar.reshape(5,2)
print(ar1)

ar2 = (np.arange(1,5))
print(ar2)


[[5 2 4 2 5]
 [9 9 3 3 8]]
[[5 2]
 [4 2]
 [5 9]
 [9 3]
 [3 8]]
[1 2 3 4]


In [ ]:
Sample = np.array([[1,2],[3,4],[5,6],[7,8]])
Sample.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
Sample = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
Sample[0:3,1]

array([2, 5, 8])

In [ ]:
Array1 = np.arange(20,2) 
Array2 = np.array([1,2,3,4,5,6,7,8,9,10])

print(Array1)
# Array3 = np.stack((Array1, Array2), axis = 1)

[]


In [ ]:
array1 = np.array([[1,2],[3,4]]) 
array2 = np.array([[5,6],[7,8]])
np.stack((array1, array2), axis = 1)


array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [ ]:
A = np.array([[4],[12],[29]]) 
B = np.array([[13],[21],[4]])
A, B = A.flatten(), B.flatten()
np.cross(A, B)

array([-561,  361,  -72])

In [ ]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25]) 
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])

my_rho = np.corrcoef(A, B)
my_rho

array([[1., 1.],
       [1., 1.]])

In [ ]:
sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}

r = sample.items()
d = list(r)
np.array(d)

<ipython-input-59-7e8d6776ffef>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(d)


array([[1, list([1, 2])],
       [2, list([[1], [2]])],
       [3, list([[1, 2], [3, 4], [4, 5]])],
       [4, list([1])],
       [5, list([1, 2, 3, 4, 5])]], dtype=object)

In [ ]:
arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])

a = np.array([8,7,9])
b = np.array([1,4,7])
print(a-b)

[7 3 2]


In [ ]:
# What will be output for the following code?
# import numpy as np
# a = np.array([3, 7, 32], dtype = complex)
# print(a)

# Marked Answer :
# [ 3.0+0.j 7.0+0.j 32.0+0.j]

# Correct Answer :
# [ 3.+0.J 7.+0.J 32.+0.J]

# TOTAL MARKS : 1MARKS OBTAINED  0

In [ ]:
# For the given arrays, array1 and array2, if we stack the two arrays row wise, what will be
# the output?
# array1 = np.array([[1,2],[3,4]])
# array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

# Marked Answer :
# None of the above

# Correct Answer :
# ARRAY([[ 1, 2],[ 3, 4],[ 1, 2],[ 3, 4],[ 5, 6],[ 7, 8],[ 9, 10]])

# TOTAL MARKS : 1MARKS OBTAINED  0

In [ ]:
# For the given arrays, array1 and array2, if we stack the two arrays column wise, what will
# be the output?
# array1 = np.array([[1,2],[3,4]])
# array2 = np.array([[5,6],[7,8]])

# Marked Answer :
# array([[1, 2], [5, 6],[3, 4], [7, 8]])

# Correct Answer :
# ARRAY([[1, 2, 5, 6],[3, 4, 7, 8]])

# TOTAL MARKS : 1MARKS OBTAINED  0